export * from './auth.controller'
export * from './user.controller'
export * from './acessgroup.controller'
export * from './course.controller'
export * from './episode.controller'
export * from './instructor.controller'
export * from './subscriptionrecord.controller'